version: '3'

networks:
  icsnetwork_ics:
    external: true

services:
  attacker:
    image: attacker:latest
    working_dir: /attacker
    volumes:
      - ../../attacker:/attacker
    command: sh -c "./injection_attack -h ${IP_PLC} -f ${FREQ}" #command: tail -F anything #container running forever
    networks:
      - icsnetwork_ics
